#' @include live_connection.R
NULL

# dispatch_query S4 generic -----------------------------------------------

#' Execute a parsed source query against a live connection
#'
#' Implemented by each backend (LiveRestConnection, LiveFhirConnection, etc.).
#'
#' @param conn A LiveConnection object.
#' @param source_query A named list produced by \code{map_to_source()}.
#' @param ... Passed to the method.
#' @return A data.frame.
#' @export
setGeneric("dispatch_query",
  function(conn, source_query, ...) standardGeneric("dispatch_query")
)

# Main entry point --------------------------------------------------------

#' Execute intercepted dbplyr SQL against the live source
#'
#' Called by \code{dbGetQuery} and \code{dbSendQuery} on LiveConnection.
#' Parses the SQL, applies the schema map, dispatches to the backend, and
#' maps result columns back to property IDs.
#'
#' @param conn A LiveConnection.
#' @param sql A SQL string (generated by dbplyr).
#' @return A data.frame.
#' @keywords internal
live_execute <- function(conn, sql) {
  sql_str <- trimws(as.character(sql))

  # Parse the dbplyr-generated SQL into a structured spec
  parsed <- parse_live_query(sql_str)

  if (is.na(parsed$table)) {
    return(data.frame(stringsAsFactors = FALSE))
  }

  # Schema detection: dbplyr calls SELECT * FROM "T" WHERE (0 = 1)
  if (parsed$is_schema_query) {
    schema <- conn@schema_map[[parsed$table]]
    if (is.null(schema)) {
      return(data.frame(stringsAsFactors = FALSE))
    }
    prop_names <- names(schema$columns)
    out <- as.data.frame(
      matrix(nrow = 0L, ncol = length(prop_names)),
      stringsAsFactors = FALSE
    )
    names(out) <- prop_names
    return(out)
  }

  # Cache check
  cache_key <- NULL
  if (!is.null(conn@cache)) {
    cache_key <- make_live_cache_key(conn, sql_str)
    cached    <- conn@cache$get(cache_key)
    if (!cachem::is.key_missing(cached)) return(cached)
  }

  # Apply schema_map: property IDs → source field names
  source_query <- map_to_source(conn, parsed)

  # Execute against the live source
  result <- dispatch_query(conn, source_query)

  # Map result columns back to property IDs
  result <- map_from_source(conn, parsed$table, result)

  # Store in cache
  if (!is.null(conn@cache) && !is.null(cache_key)) {
    conn@cache$set(cache_key, result)
  }

  result
}

# SQL parser --------------------------------------------------------------

#' Parse a dbplyr-generated SQL SELECT into a structured spec
#'
#' @param sql_str Character scalar. SQL string.
#' @return A named list with: table, select, filters, limit, offset,
#'   is_schema_query, sql.
#' @keywords internal
parse_live_query <- function(sql_str) {
  # Schema detection patterns
  is_schema_query <-
    grepl("WHERE\\s*\\(\\s*0\\s*=\\s*1\\s*\\)", sql_str,
          perl = TRUE, ignore.case = TRUE) ||
    grepl("WHERE\\s+FALSE\\b",  sql_str, perl = TRUE, ignore.case = TRUE) ||
    grepl("LIMIT\\s+0\\b",      sql_str, perl = TRUE, ignore.case = TRUE)

  # Table name: FROM "TableName"
  tbl_m <- regmatches(sql_str,
    regexpr('(?i)FROM\\s+"([^"]+)"', sql_str, perl = TRUE))
  table <- if (length(tbl_m) && nchar(tbl_m)) {
    sub('(?i)FROM\\s+"([^"]+)"', "\\1", tbl_m, perl = TRUE)
  } else {
    # Unquoted table name fallback
    m2 <- regmatches(sql_str, regexpr('(?i)FROM\\s+(\\w+)', sql_str, perl = TRUE))
    if (length(m2) && nchar(m2)) sub("(?i)FROM\\s+", "", m2, perl = TRUE) else NA_character_
  }

  # SELECT columns
  sel_raw <- sub("(?i)SELECT\\s+(.*?)\\s+FROM.*", "\\1", sql_str, perl = TRUE)
  select <- if (trimws(sel_raw) == "*") {
    NULL
  } else {
    m <- gregexpr('"([^"]+)"', sel_raw, perl = TRUE)
    hits <- regmatches(sel_raw, m)[[1]]
    if (length(hits)) gsub('"', "", hits) else NULL
  }

  # WHERE filters
  where_str <- extract_where_string(sql_str)
  filters <- if (!is_schema_query && !is.null(where_str)) {
    parse_where_conditions(where_str)
  } else {
    list()
  }

  # LIMIT
  lim_m <- regmatches(sql_str,
    regexpr("(?i)LIMIT\\s+(\\d+)", sql_str, perl = TRUE))
  limit <- if (length(lim_m) && nchar(lim_m)) {
    as.integer(sub("(?i)LIMIT\\s+", "", lim_m, perl = TRUE))
  } else {
    NULL
  }

  # OFFSET
  off_m <- regmatches(sql_str,
    regexpr("(?i)OFFSET\\s+(\\d+)", sql_str, perl = TRUE))
  offset <- if (length(off_m) && nchar(off_m)) {
    as.integer(sub("(?i)OFFSET\\s+", "", off_m, perl = TRUE))
  } else {
    0L
  }

  list(
    table           = table,
    select          = select,
    filters         = filters,
    limit           = limit,
    offset          = offset,
    is_schema_query = is_schema_query,
    sql             = sql_str
  )
}

extract_where_string <- function(sql_str) {
  m <- regmatches(sql_str, regexpr(
    "(?i)WHERE\\s+(.+?)(?=\\s+(?:LIMIT|ORDER\\s+BY|GROUP\\s+BY|HAVING)\\b|$)",
    sql_str, perl = TRUE
  ))
  if (!length(m) || !nchar(m)) return(NULL)
  sub("(?i)^WHERE\\s+", "", m, perl = TRUE)
}

parse_where_conditions <- function(where_str) {
  where_str <- trimws(where_str)
  # Strip single outer parens wrapper if present
  if (startsWith(where_str, "(") && endsWith(where_str, ")")) {
    inner <- substr(where_str, 2L, nchar(where_str) - 1L)
    # Only strip if the parens match
    if (paren_depth(inner) == 0L) where_str <- inner
  }
  parts   <- split_on_and(where_str)
  filters <- Filter(Negate(is.null), lapply(parts, function(p) {
    parse_single_condition(trimws(p))
  }))
  filters
}

paren_depth <- function(s) {
  depth <- 0L
  for (ch in strsplit(s, "")[[1]]) {
    if (ch == "(") depth <- depth + 1L
    else if (ch == ")") depth <- depth - 1L
    if (depth < 0L) return(-1L)
  }
  depth
}

split_on_and <- function(s) {
  chars   <- strsplit(s, "")[[1]]
  n       <- length(chars)
  parts   <- character(0)
  current <- character(0)
  depth   <- 0L
  i       <- 1L

  while (i <= n) {
    ch <- chars[i]
    if (ch == "(") { depth <- depth + 1L; current <- c(current, ch); i <- i + 1L; next }
    if (ch == ")") { depth <- depth - 1L; current <- c(current, ch); i <- i + 1L; next }

    # Check for AND keyword at depth 0 (surrounded by spaces)
    if (depth == 0L && i + 2L <= n) {
      chunk <- paste(chars[i:min(i + 2L, n)], collapse = "")
      if (toupper(chunk) == "AND") {
        before_ok <- i == 1L || chars[i - 1L] %in% c(" ", "\t", ")")
        after_ok  <- i + 3L > n || chars[i + 3L] %in% c(" ", "\t", "(")
        if (before_ok && after_ok) {
          parts   <- c(parts, trimws(paste(current, collapse = "")))
          current <- character(0)
          i       <- i + 3L
          next
        }
      }
    }
    current <- c(current, ch)
    i <- i + 1L
  }
  if (length(current)) parts <- c(parts, trimws(paste(current, collapse = "")))
  parts[nchar(parts) > 0L]
}

parse_single_condition <- function(cond) {
  cond <- trimws(cond)
  # Strip matching outer parens
  while (startsWith(cond, "(") && endsWith(cond, ")") && paren_depth(substr(cond, 2L, nchar(cond) - 1L)) == 0L) {
    cond <- trimws(substr(cond, 2L, nchar(cond) - 1L))
  }

  # Ignore schema sentinel conditions
  if (grepl("^0\\s*=\\s*1$", cond) || grepl("^(?i)FALSE$", cond)) return(NULL)

  # IS NULL / IS NOT NULL
  if (grepl('"[^"]+\"\\s+IS\\s+NOT\\s+NULL', cond, perl = TRUE, ignore.case = TRUE)) {
    col <- sub('"([^"]+)"\\s+IS\\s+NOT\\s+NULL.*', "\\1", cond, perl = TRUE, ignore.case = TRUE)
    return(list(column = col, op = "IS NOT NULL", value = NULL))
  }
  if (grepl('"[^"]+\"\\s+IS\\s+NULL', cond, perl = TRUE, ignore.case = TRUE)) {
    col <- sub('"([^"]+)"\\s+IS\\s+NULL.*', "\\1", cond, perl = TRUE, ignore.case = TRUE)
    return(list(column = col, op = "IS NULL", value = NULL))
  }

  # IN (...)
  if (grepl('"[^"]+"\\s+IN\\s*\\(', cond, perl = TRUE, ignore.case = TRUE)) {
    col      <- sub('"([^"]+)"\\s+IN\\s*\\(.*', "\\1", cond, perl = TRUE, ignore.case = TRUE)
    vals_str <- sub('.*IN\\s*\\((.+)\\)\\s*$', "\\1", cond, perl = TRUE, ignore.case = TRUE)
    return(list(column = col, op = "IN", value = parse_value_list(vals_str)))
  }

  # NOT IN (...)
  if (grepl('"[^"]+"\\s+NOT\\s+IN\\s*\\(', cond, perl = TRUE, ignore.case = TRUE)) {
    col      <- sub('"([^"]+)"\\s+NOT\\s+IN\\s*\\(.*', "\\1", cond, perl = TRUE, ignore.case = TRUE)
    vals_str <- sub('.*NOT\\s+IN\\s*\\((.+)\\)\\s*$', "\\1", cond, perl = TRUE, ignore.case = TRUE)
    return(list(column = col, op = "NOT IN", value = parse_value_list(vals_str)))
  }

  # LIKE
  if (grepl('"[^"]+"\\s+LIKE\\s+', cond, perl = TRUE, ignore.case = TRUE)) {
    col     <- sub('"([^"]+)"\\s+LIKE\\s+.*', "\\1", cond, perl = TRUE, ignore.case = TRUE)
    val_str <- trimws(sub('"[^"]+"\\s+LIKE\\s+', "", cond, perl = TRUE, ignore.case = TRUE))
    return(list(column = col, op = "LIKE", value = parse_single_value(val_str)))
  }

  # Comparison: >=, <=, !=, <>, >, <, =
  for (op in c(">=", "<=", "!=", "<>", ">", "<", "=")) {
    pat <- paste0('"([^"]+)"\\s*', gsub("([<>=!])", "\\\\\\1", op), '\\s*(.+)')
    if (grepl(pat, cond, perl = TRUE)) {
      col     <- sub(pat, "\\1", cond, perl = TRUE)
      val_str <- trimws(sub(pat, "\\2", cond, perl = TRUE))
      norm_op <- if (op == "<>") "!=" else op
      return(list(column = col, op = norm_op, value = parse_single_value(val_str)))
    }
  }

  # Unknown — pass through as a raw SQL fragment (no push-down)
  list(column = NULL, op = "RAW_SQL", value = cond)
}

parse_single_value <- function(s) {
  s <- trimws(s)
  if (startsWith(s, "'") && endsWith(s, "'")) return(substr(s, 2L, nchar(s) - 1L))
  if (grepl("^-?\\d+\\.?\\d*$", s)) return(as.numeric(s))
  if (toupper(s) == "TRUE")  return(TRUE)
  if (toupper(s) == "FALSE") return(FALSE)
  if (toupper(s) == "NULL")  return(NA)
  s
}

parse_value_list <- function(s) {
  # Split on commas not inside quotes
  parts <- character(0)
  current <- ""
  in_quote <- FALSE
  for (ch in strsplit(s, "")[[1]]) {
    if (ch == "'" && !in_quote) { in_quote <- TRUE;  next }
    if (ch == "'" &&  in_quote) { in_quote <- FALSE; next }
    if (ch == "," && !in_quote) { parts <- c(parts, trimws(current)); current <- ""; next }
    current <- paste0(current, ch)
  }
  if (nchar(trimws(current))) parts <- c(parts, trimws(current))
  sapply(parts, parse_single_value, USE.NAMES = FALSE)
}

# Schema mapping ----------------------------------------------------------

#' Map parsed query property IDs to source field names
#' @keywords internal
map_to_source <- function(conn, parsed) {
  schema <- conn@schema_map[[parsed$table]]
  if (is.null(schema)) {
    cli::cli_abort("No schema_map entry for object type {.val {parsed$table}}.")
  }
  col_map <- schema$columns  # property_id → source_field

  # Map SELECT columns
  source_select <- if (is.null(parsed$select)) {
    NULL
  } else {
    vapply(parsed$select, function(p) col_map[[p]] %||% p, character(1))
  }

  # Map filter columns to source field names
  source_filters <- lapply(parsed$filters, function(f) {
    if (!is.null(f$column)) {
      f$source_column <- col_map[[f$column]] %||% f$column
    }
    f
  })

  list(
    resource        = schema$resource,
    pk              = schema$pk,
    select          = source_select,
    filters         = source_filters,
    limit           = parsed$limit,
    offset          = parsed$offset,
    is_schema_query = parsed$is_schema_query,
    sql             = parsed$sql,
    table           = parsed$table
  )
}

#' Map source result columns back to property IDs
#' @keywords internal
map_from_source <- function(conn, table_name, df) {
  schema <- conn@schema_map[[table_name]]
  if (is.null(schema) || nrow(df) == 0L && ncol(df) == 0L) return(df)

  col_map <- schema$columns  # property_id → source_field
  inv_map <- stats::setNames(names(col_map), unname(unlist(col_map)))

  new_names <- vapply(names(df), function(n) inv_map[[n]] %||% n, character(1))
  names(df) <- new_names
  df
}

#' Reconstruct a SQL SELECT from a mapped source_query
#' @keywords internal
reconstruct_sql <- function(sq) {
  sel <- if (is.null(sq$select) || length(sq$select) == 0L) {
    "*"
  } else {
    paste(paste0('"', sq$select, '"'), collapse = ", ")
  }
  from_clause <- paste0('"', sq$resource, '"')

  where_parts <- vapply(sq$filters, function(f) {
    col_expr <- if (!is.null(f$source_column)) {
      paste0('"', f$source_column, '"')
    } else {
      f$value  # RAW_SQL
    }
    switch(f$op,
      "IS NULL"     = paste0(col_expr, " IS NULL"),
      "IS NOT NULL" = paste0(col_expr, " IS NOT NULL"),
      "IN"          = paste0(col_expr, " IN (",
                              paste(vapply(f$value, sql_lit, character(1)), collapse = ", "), ")"),
      "NOT IN"      = paste0(col_expr, " NOT IN (",
                              paste(vapply(f$value, sql_lit, character(1)), collapse = ", "), ")"),
      paste0(col_expr, " ", f$op, " ", sql_lit(f$value))
    )
  }, character(1))

  where_clause <- if (length(where_parts)) {
    paste("WHERE", paste(where_parts, collapse = " AND "))
  } else ""

  lim  <- if (!is.null(sq$limit))  paste("LIMIT", sq$limit)  else ""
  off  <- if (!is.null(sq$offset) && sq$offset > 0L) paste("OFFSET", sq$offset) else ""

  parts <- c(paste("SELECT", sel), paste("FROM", from_clause),
             where_clause, lim, off)
  paste(parts[nchar(trimws(parts)) > 0L], collapse = " ")
}

sql_lit <- function(v) {
  if (is.null(v) || (length(v) == 1L && is.na(v))) return("NULL")
  if (is.numeric(v) || is.logical(v)) return(as.character(v))
  paste0("'", gsub("'", "''", as.character(v)), "'")
}

# Cache helpers -----------------------------------------------------------

make_live_cache_key <- function(conn, sql_str) {
  id <- paste0(conn@source_type, ":", paste(names(conn@schema_map), collapse = ","))
  raw <- paste(id, sql_str, sep = "|")
  as.character(sum(utf8ToInt(substr(raw, 1L, 255L))) %% 1e9)
}

`%||%` <- function(a, b) if (is.null(a)) b else a
